crates/as/index.ts, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/src/lib.rs, tests/as/package-lock.json, tests/as/package.json
Also:
- Make the `ptr` and `len` order consistent (it was flipped for response headers)
- Make the naming consistent, too (`err_written_ptr`)
- Use more accurate raw pointer types
- Update `as-wasi`
=> Change the req() prototype to directly accept constant lengths

crates/as/index.ts, crates/as/tsconfig.json, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/Cargo.toml, crates/wasi-experimental-http/src/lib.rs
Since RFC7230 prohibites delimiters in header names, and control characters in values, headers can safely be encoded as
```text
<header>:<value>\n
<header>:<value>\n
...
```
This is printable, simple and fast to serialize/deserialize, and matches how headers are sent in HTTP 1.x
Fixes #35
=> Don't require JSON for header serialization

crates/as/index.ts, tests/as/index.ts, tests/as/package-lock.json, tests/rust/src/lib.rs
This commit introduces a few changes to the way headers are handled
in AssemblyScript:
- fix the way headers are parsed in AssemblyScript.
Specifically, after the request headers were not sent as JSON anymore,
there was an additional pair of quotation marks for both header key and
value that wasn't properly escaped.
- remove the additional quotation pair and bring the AssemblyScript way 
of passing strings back in sync with the way this is done in Rust.
- update the response headers in AssemblyScript to be a
much easier to consume `Map<string, string>` rather than a plain string
- update the tests to check the response status and  number of headers 
returned by the server, and abort if any of them doesn't match.
cc @jedisct1
=> Fix header parsing in AssemblyScript and return a header map rather than a string

crates/wasi-experimental-http-wasmtime/readme.md, crates/wasi-experimental-http-wasmtime/src/lib.rs, readme.md, tests/integration.rs
closes #37
depends on #38 
This commit renames `allowed_domains` to `allowed_hosts` and defaults
to NOT allowing guest modules to make HTTP requests when `None` is
the value passed.
This change brings the way this library handles its "capability" closer
to how upstream WASI works, while also making more sense (if `None` is
passed as value for `allowed_hosts`, modules are not allowed to send
requests).
=> Disable `allowed_hosts` by default

crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml, readme.md
This PR updates the package versions to 0.2.
Note that the versions have already been published to crates.io and NPM:
- https://crates.io/crates/wasi-experimental-http
- https://crates.io/crates/wasi-experimental-http-wasmtime
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http
=> Bump package versions to 0.2

Cargo.toml, crates/as/index.ts, crates/as/package-lock.json, crates/as/package.json, crates/as/readme.md, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http-wasmtime/readme.md, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/Cargo.toml, crates/wasi-experimental-http/src/lib.rs, readme.md, tests/as/index.ts, tests/as/package-lock.json, tests/as/package.json, tests/integration.rs, tests/rust/src/lib.rs
Hi!
This is a proposal to support streaming (at least in the API and for responses), avoid the `alloc` function, and simplify the current implementation while making it closer to other WASI proposals.
`req()` now returns a handle to a `Response` object, along with the status code.
A `Response` object can be then used to:
- Read individual headers
- Read the body in a streaming fashion.
A `body_read()` function pulls as many bytes as the client wants, and returns `0` when the end of the stream is reached.
This makes it compatible with streaming, doesn't require any dynamic memory allocation, and allows the client to control the maximum response size it's willing to accept.
For conveniency, the Rust and AssemblyScript bindings also have a `readAll` function that reads everything until the …
=> Change the API to allow streaming & no callback to alloc

crates/as/index.ts, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/src/lib.rs, tests/as/package-lock.json, tests/integration.rs
This commit updates the Rust Wasmtime and guest implementations with
some more detailed comments, and slightly refactors and renames a few
structs, particularly `Http` -> `HttpCtx`.
=> Add comments to Rust implementation

witx/wasi_experimental_http.witx
Rust and AssemblyScript definitions for guest APIs can be automatically generated from this using [witx-codegen](https://github.com/jedisct1/witx-codegen).
=> Add WITX interface definitions

crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/src/lib.rs, tests/as/index.ts, tests/integration.rs, tests/rust/src/lib.rs
This commit adds a runtime option to limit the maximum number of
concurrent requests a guest module can make.
If set, the runtime implementation checks the current number of open
handles and if it exceeds the limit, the current request will fail.
Note that this does not affect the default (set as `None`), in which
case guests can send as many requests as they want.
This affects the "un-closed" handles - for example, if a Rust `Response`
goes out of scope, `Drop` will be automatically executed and the handle
closed, so the request does not count towards the limit.
On the other hand, the current AssemblyScript implementation requires
the guest to manually close the handle, so this could have an impact.
A subsequent change to the AssemblyScript implementation should
implement a GC finalizer …
=> Add option to limit maximum concurrent requests

.gitignore, build.rs, crates/as/index.ts, crates/as/raw.ts, crates/as/readme.md, crates/wasi-experimental-http-wasmtime/readme.md, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/readme.md, crates/wasi-experimental-http/src/lib.rs, crates/wasi-experimental-http/src/raw.rs, readme.md, tests/as/index.ts, tests/rust/src/lib.rs, witx/readme.md, witx/wasi_experimental_http.witx
closes #55 
This commit adds a new hostcall in the library, together with client
implementation for getting the entire response header map for a given
request.
TODO:
=> Add `headers_get_all` hostcall and client

witx/readme.md, witx/wasi_experimental_http.witx
The witx syntax was changed to [require types to be included in the module](https://github.com/alexcrichton/WASI/commit/59e67ae8b820b834101b748c1b6efb3f6765f8eb) itself.
`witx-codegen` was updated for the new syntax.
Update our witx file for that change.
The output code remains the same.
=> Update the witx file syntax

.github/workflows/rust.yml, .gitignore, build.rs, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http-wasmtime/src/lib.rs, tests/as/index.ts
This commit removes the dependency on the client library from the
Wasmtime library in order to fix a Windows linking error.
Specifically, the Windows error stems from the fact that the client
library, which is mainly used for building Wasm modules, imports the
functions related to sending HTTP requests from the runtime.
There seems to be a bug in the Windows linker resulting in a linking
error, even if the Wasmtime crate is not calling any of the external
symbols, and this commit removes that dependency entirely, given that
the used functionality was limited to a single function.
See https://github.com/rust-lang/rust/issues/86125.
This also simplifies `build.rs`, ensuring it should run properly on both
Unix and Windows systems, and updates the GitHub action to compile on
Linux, macOS, and …
=> Remove client dep to fix Windows

build.rs
This PR finally fixes all the CI errors for this repo by 
updating the `witx-codegen` version used to generate the 
language bindings.
=> Update witx-codegen version used in build script

Cargo.toml, bin/wasmtime-http.rs, readme.md
closes #56 
This commit adds a new binary target to the Cargo workspace that
mimics the `wasmtime run` command, and instantiates and executes modules
importing `wasi_experimental_http`.
The implementation uses most of the test harness from `integration.rs`,
and handles args and environment variables in the same way as Wasmtime.
Future commits should handle directory mapping as well.
=> Add bin that instantiates modules importing HTTP

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml
Updated the tags to v0.4.0 and published to NPM and Crates.io:
- https://crates.io/crates/wasi-experimental-http/0.4.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.4.0
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.4.0
=> Bump packages to v0.4.0 to bring in sync with latest published releases

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml
This PR updates the versions of the packages to v0.5.0:
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.5.0
- https://crates.io/crates/wasi-experimental-http/0.5.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.5.0
=> Update versions to v0.5.0

Cargo.toml, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http-wasmtime/src/lib.rs, crates/wasi-experimental-http/Cargo.toml, crates/wasi-experimental-http/src/lib.rs, tests/integration.rs, tests/rust/Cargo.toml
This commit updates Wasmtime to v0.30 due to a security advisory - see https://rustsec.org/advisories/RUSTSEC-2021-0110.html.
It also adds a utility function that makes it easy to use the library with a generic linker -- the previous `add_to_linker` implementation was unusable for any runtime that had a different kind of internal state.
This commit adds a generic function that accepts a `Linker<T>`.
=> Add a generic `add_to_linker` function that accepts generic stores and update Wasmtime

Cargo.toml, bin/wasmtime-http.rs, crates/wasi-experimental-http-wasmtime/Cargo.toml, tests/integration.rs
This PR updates Wasmtime to the latest version, v0.31.
=> Update Wasmtime to v0.31

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml
See published packages:
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.7.0
- https://crates.io/crates/wasi-experimental-http/0.7.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.7.0
=> chore: update package versions to v0.7.0

bin/wasmtime-http.rs, tests/as/index.ts, tests/rust/src/lib.rs
This commit enables the multi-memory and module linking proposals in
Wasmtime.
=> feat: enable multi-memory and module linking

Cargo.toml, crates/wasi-experimental-http-wasmtime/Cargo.toml
depends on #80 
This commit updates Wasmtime to v0.33.
=> chore: update Wasmtime to v0.33 

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml
See published packages:
- https://crates.io/crates/wasi-experimental-http/0.8.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.8.0
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.8.0
=> Update version to 0.8.0

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http/Cargo.toml
See packages:
- https://crates.io/crates/wasi-experimental-http/0.9.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.9.0
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.9.0
=> chore: update Wasmtime to v0.34 and bump packages to v0.9.0

bin/wasmtime-http.rs, crates/wasi-experimental-http-wasmtime/Cargo.toml, crates/wasi-experimental-http-wasmtime/src/lib.rs, tests/integration.rs
BREAKING CHANGE: The type of this parameter has changed from `impl Fn(&T) ->
&HttpCtx + Send + Sync + Copy + 'static` to `impl Fn(&T) -> HttpCtx + Send +
Sync + 'static`.  Besides removing the `Copy` bound (which wasn't needed), I've
changed the return type from `&HttpCtx` to `HttpCtx`.
The rationale for this is that the return value of `get_cx` was effectively
being cloned anyway immediately after calling it, so there was no efficiency
gain from returning a reference.  Also, any implementation of the original type
would have to ensure the returned reference has the same lifetime as the context
parameter, which essentially means the implementation is forced to store the
`HttpCtx` inside the context.  That's overkill for e.g. `wagi`, which has no
need for per-context HTTP configuration. …
=> refactor!: change type of `HttpState::add_to_linker`'s `get_cx` parameter

Cargo.toml, crates/as/package.json, crates/wasi-experimental-http/Cargo.toml
See published packages:
- https://crates.io/crates/wasi-experimental-http/0.10.0
- https://crates.io/crates/wasi-experimental-http-wasmtime/0.10.0
- https://www.npmjs.com/package/@deislabs/wasi-experimental-http/v/0.10.0
=> chore: update package versions to v0.10.0
